//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace celestia_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public Board()
        {
            this.Threads = new HashSet<Thread>();
        }
    
        public int board_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
