//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace celestia_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Threads1 = new HashSet<Thread>();
        }
    
        public int thread_id { get; set; }
        public Nullable<int> parent_thread { get; set; }
        public Nullable<int> board_id { get; set; }
        public string user_cookie_id { get; set; }
        public string thread_caption { get; set; }
        public string content { get; set; }
        public byte[] image { get; set; }
        public string image_file_name { get; set; }
        public Nullable<int> image_file_size { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> pin { get; set; }
        public Nullable<bool> is_user_mod { get; set; }
        public Nullable<bool> is_reply_to_op { get; set; }
        public Nullable<bool> is_op_reply { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ICollection<Thread> Threads1 { get; set; }
        public virtual Thread Thread1 { get; set; }
    }
}
